### PR TITLE
Add propertyName to the attachment's defaultUrl

### PR DESCRIPTION
**Pull request by jonstorer**
- allows multiple attachments with the same styles
- add devDependencies on `mocha`, `chai`, & `mongoose`
- add `npm run specs`
- update `npm test` => `"npm run specs & node ./test/testFindImageMagickFormats.js"`

### CODE REVIEW

**Comment by bithavoc** [comment]
@jonstorer thank you for this contribution, should I publish to NPM as soon as Travis-CI says OK?

**Comment by jonstorer** [comment]
@bithavoc That'd be nice. We're currently using our forked branch, I'd like to get back on the published version.

Also, the knox strategy is not compatible with master of this repo. Is that scheduled or are you looking for contributors?

**Comment by bithavoc** [comment]
I'm looking for contributors for all the repos: knox, aws-s3 and knox.

Btw I don't think you added yourself to AUTHORS.

Are you interested in maintaining knox? I'll publish to NPM when it's necessary.

**Comment by jonstorer** [comment]
@bithavoc How would you like me to add myself now that you've merged? I'll do it next time I make a change. I can look at knox to see about updating it. We just switched to aws2js since it was working and had little configuration change.

**Comment by bithavoc** [comment]
You can add yourself anytime, if you send another PR I'll accept it.

@jonstorer you said mongoose-attachments wasn't compatible with knox, is this still the case?

**Comment by jonstorer** [comment]
@bithavoc when I switched to this version of mongoose-attachments, I got errors that mongoose-attachments-knox did not have a getUrl method defined. I created an issue on that repo. https://github.com/heapsource/mongoose-attachments-knox/issues/3

**Pull request merged**
