### PR TITLE
Include localfs provider file

### PR DESCRIPTION
**Pull request by joewright**

### CODE REVIEW

**Comment by bithavoc** [comment]
Hi @joewright,

We are actually splitting the providers in separate projects.

Check https://github.com/firebaseco/mongoose-attachments/pull/10

Check the other providers:

https://github.com/firebaseco/mongoose-attachments-localfs
https://github.com/firebaseco/mongoose-attachments-aws2js
https://github.com/firebaseco/mongoose-attachments-knox

Can you help us removing the providers out of mongoose-attachments and updating the readme to encourage the user of the other modules? Once this is ready, I will publish the four modules to NPM.

**Comment by joewright** [comment]
Thanks for pointing me in the right direction for localfs.

Do you want the three providers to be dependencies of mongoose-attachments,
or to scrap the providers in mongoose-attachments and leave the other 3 as
standalone modules?

**Comment by bithavoc** [comment]
When all the proper changes are made, We will have four modules:
- mongoose-attachments without any provider
- -localfs depending on mongoose-attachments
- -aws2js depending on mongoose-attachments
- -knox depending on mongoose-attachments

The problem is that both `knox` and `aws2js` uses heavy xml modules that have to be installed in order to use a simple module like `localfs`.

At the end, `mongoose-attachments` should do all the imagemagick heavy lifting but it should not have any implementation.

It would be awesome if you create a pull request to do the following:
- Remove all the references to these providers(they are already in separate modules): https://github.com/firebaseco/mongoose-attachments/tree/master/lib/providers
- Update Readme.md to explain all these changes and create links with descriptions to the new modules.

Cheers.

**Comment by nuarhu** [comment]
Great, thanks, Joe!

@thepumpkin1979 - the changes look fine to me. :+1: 

Happy New Year, by the way. :-)

**Comment by joewright** [comment]
Thank you, happy New Year to you too!

**Comment by bithavoc** [comment]
@nuarhu We need to merge these changes, don't we?

**Pull request closed without merging**
