### PR TITLE
FsStorage : provider implementation to store images in local file system

### PR DESCRIPTION
**Pull request by nuarhu**
Hi Johan,

I have created another provider to store the images locally which I am allowed to contribute (by courtesy of IT Agenten https://github.com/itagenten).

Disclaimer:
We have been using this FsStorage for a while, now, but only in testing envrionments. Also, the script was (is still) a part of our app, I have not added it to the mongoose-attachments module until right now. Meaning: it has not been tested with that same setup.

Have a look at it and if you would like to pull it in I will change our code to use it as part of mongoose-attachments and run our regression tests on it.

Cheers,
Chantal

EDIT: This pull requests includes the commits from https://github.com/firebaseco/mongoose-attachments/pull/9 . I did hope GitHub would remove them once you've accepted No 9 - but it doesn't seem to work that way...

### CODE REVIEW

**Comment by bithavoc** [comment]
Hi @nuarhu ,

What you need to do is create a branch locally in your development machine:

```
git checkout -b my_new_feature
```

You can make your changes now and commit them.

In order to make a pull request, you push to your origin/fork at a new branch with the same name.

```
git push origin my_new_feature
```

Once you push to a branch in github, github UI will provision some actions in the page of your repo to quickly make pull requests with whatever you commited to that branch.

Once you made the pull request and I integrate it into master, you switch to `master` locally in your machine:

```
git checkout master
```

And pull the changes from upstream(this original proyecto you've forked).

(If you haven't added upstream to your local repo:)

```
git remote add upstream git://github.com/firebaseco/mongoose-attachments.git
```

Pull the changes that I've merged into master.

```
git pull upstream master
```

Now you are ready to do `git checkout -b my_another_feature` locally. Rinse and Repeat :)

**Comment by bithavoc** [comment]
About the FsStorage,

I think it's time to split this module as:
- mongoose-attachments-knox
- mongoose-attachments-aws2js
- mongoose-attachments-fsstorage

We still need to support Rackspace CloudFiles, so it makes sense to me to perform these changes now. The current version is 0.0.4, we would jump to 0.1.0 if we do this.

I want to hear your thoughts on this.

**Comment by nuarhu** [comment]
About branching:
Ok. I did create a branch: https://github.com/nuarhu/mongoose-attachments/tree/fsstorage
However, that was after I changed the README on the master to create pull request No 9. So, the branch was ahead of your master and I guess that is why the two commits were included when I created pull request No 10. I did hope that when I merged the changes from your master back into my branch fsstorage (after you accepted No 9) that they would be removed but that is not the case. :-(
There must be a way though, I might have to try creating another pull request - and make a bit of a mess of it. I know, I should have used branches right from the start before creating any pull request. Lesson learned.

EDIT: ha, it worked - I forgot the "git pull" (was using fetch and merge and whatever). Thanks for the detailed information!

About the splitting:
That looks good. Reminds me of how passport.js does it, and I do like it.
I'm not sure about the name. I called the class "FsStorage" because the AmazonS3 one is called S3Storage. But I called the module file 'localfs' which might transport more meaning than "FsStorage". Maybe the module should be named mongoose-attachments-localfs? That might allow for a hyphothetical module mongoose-attachments-distributedfs or else.

**Comment by bithavoc** [comment]
do you need this `localfsp`  feature in NPM anytime soon?

Because I lack of time to split the modules today. Although, I could do it later this week and publish the three modules.

Do you want me to create the other three repos, add you as a commiter and you help me split them? :)

**Comment by nuarhu** [comment]
On second thought:
If we split we should make sure that when the storage modules are upgraded to a newer version of the core dependency they are (regression) tested sufficiently.

I will think about how to test the core module and the storages. It might make sense to require certain binaries/services for the specific tests to be present - like Mongo, ImageMagick and others.

**Comment by bithavoc** [comment]
yeah, we can use wildcard versions in all the storage modules:

```
"mongoose-attachments": "*"
```

That will do the trick.

I just added you to the other repos.

If you use skype, please add me `thepumpkin1979`. My email is `johan@firebase.co` if you need anything.

**Comment by nuarhu** [comment]
No, I don't need them anytime soon - the app does not depend on it as it still runs with the original version.
Let's not rush that change.

Yes, you can add me as a committer. If it's not clear to me how to proceed I'll let you know. Best would be if you started to work on one of the submodules and I could follow your example working on another.

**Comment by bithavoc** [comment]
That makes sense.

I will create the first one tomorrow.

Even when you have push/pull permissions, please continue using the branch/pull approach even when you can merge the pull requests yourself :)

**Comment by nuarhu** [comment]
Yes, I will. Although this huge green merge button keeps standing out brightly. _squint_
(Why is it that you always want to click the big green button without thinking...?)

**Comment by bithavoc** [comment]
I'm gonna merge this temporarily while we split the modules.

**Comment by bithavoc** [comment]
@nuarhu, I've migrated knox provider to this repo https://github.com/firebaseco/mongoose-attachments-knox

We still missing https://github.com/firebaseco/mongoose-attachments/blob/master/lib/providers/aws2js.js and https://github.com/firebaseco/mongoose-attachments/blob/master/lib/providers/localfs.js

Can you migrate those to their respective repos when you have some time?

Thanks.

**Comment by nuarhu** [comment]
Ok. I'll plan it for the weekend.

**Comment by bithavoc** [comment]
hey @nuarhu,

thanks for splitting all the other providers.

Since we already splitted all the providers, shall we remove then from this repo and bump the version to 1.0?

Assuming the everyone is following the [semver](http://semver.org) versioning, all they had to do is add the dependencies to the new repos and perform a `require`.

How do you think we should reflect those changes in the Readme?

It's definitely a breaking change.

**Comment by nuarhu** [comment]
Hi @thepumpkin1979,

yes, I agree: remove them and bump to 1.0. And maybe already create a "production branch" for maintenance of the current version? Could also be done at a future point when issues are reported for the old version.

In the Readme:
Looking at the current Readme, maybe we should just add notes/comments to the existing description and examples and mark those as "since 1.0". These would just contain the code that is required when using 1.0.
For example, in the sample code:

```
// var ma-knox = require('mongoose-attachments-knox'); // uncomment if using 1.0 and knox
```

Additionally, at the beginning of the Readme we could add something like a "Changes in 1.0" section so users who upgrade from a previous version quickly see the difference and where we mention the "since 1.0" notes in the remainder of the Readme.

**Pull request merged**
